import React from 'react'
import "./portfolio.css"
import Project from './project'
import { Portfolio1, Portfolio2, Portfolio3, Portfolio4, Portfolio5, Portfolio6, Portfolio7, Portfolio8 } from '../assets/images'
import {AiFillHtml5} from "react-icons/ai"
import {DiCss3} from "react-icons/di"
import {SiJavascript} from "react-icons/si"
import {DiReact} from "react-icons/di"
import {SiTypescript} from "react-icons/si"

export default function Portfolio(){
    return (
        <section id='portfolio'>
            <h5>My Recent Work</h5>
            <h2 className='trans'>Projects</h2>
            <div className='projects'>
                <Project demo="https://dariusjecu-imdb-ish.netlify.app" project="https://github.com/dariusjecu/IMDb-ish" tech={[AiFillHtml5, DiCss3, DiReact, SiTypescript]} img={Portfolio8} title={"IMDb-ish"} desc={"An IMDb clone that it is still in progress. Until now, I manage to implement the header, the hero carousel and a top-picks section, containing a carousel of the most popular shows right now. The hero carousel displays 10 best rated shows right now and let the user to see the trailer."} new={true} inProgress={true}/>
                <Project demo="https://dariusjecu-tictactoe.netlify.app" project="https://github.com/dariusjecu/TicTacToe" tech={[AiFillHtml5, DiCss3, DiReact, SiTypescript]} img={Portfolio7} title={"Tic-Tac-Toe"} desc={"The board should contain 9 clickable elements in a 3x3 grid. Each element is a square and could take one of the following values (X or O) when is clicked. The game has 2 players, player 1 being represented by value X and player 2 by value O. The player who needs to make the next move it will be shown above the game board. The game can be finished in 3 ways: if the player 1 wins, if player 2 wins or if it is a tie and the board is filled with X and O and there are no more squares to be filled. After the game is finished, a button will appear under the board to restart the game."} new={true}/>
                <Project demo="https://dariusjecu.github.io/Meme-Generator/" project="https://github.com/dariusjecu/Meme-Generator" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio3} title={"Meme Generator"} desc={"A meme generator where the user can create his own meme. Through an API, random images will be generated every time the user presses a button. You can also insert two suggestive descriptions of the image to make the meme more suggestive."}/>
                <Project demo="https://dariusjecu.github.io/Trivia-Game/" project="https://github.com/dariusjecu/Trivia-Game" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio1} title={"Trivia Game"} desc={"A trivia game in which the user can select from the main page the category (eg. mythology, mathematics, etc.), the number of questions, the difficulty and the option for the questions to be grid-type or true-or-false. The questions are generated by an API and will be displayed according to the chosen criteria. After finishing the test and pressing the 'Check' button, the correct answers and the number of correct answers of the user will be displayed on the screen."}/>
                <Project demo="https://dariusjecu.github.io/Tenzies/" project="https://github.com/dariusjecu/Tenzies" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio2} title={"Tenzies"} desc={"A game of Tenzies. The idea of the game is to get the same number on all the dice in as few attempts as possible. The dice can be locked by selecting them so that they do not change their value when the 'Roll' button is pressed. When all the dice are locked and have the same displayed value, the game is over and the user can start a new game."}/>
                <Project demo="Token" project="https://github.com/dariusjecu/Crypto_Token" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio4} title={"Crypto Token"} desc={"A token named DARK in Internet Computer blockchain, using React as frontend and Motoko as database. Each user will have a unique username for the device used. To check the username, the user can press the 'Check account' button in the second box. Each user can receive 1000 free DARK tokens by pressing the button in the first box. Users can check the number of tokens they have in their account by clicking on the button in the third box. Also, in the last box, the user can make a transfer to another account."}/>
                <Project demo="https://dariusjecu.github.io/Picsome/" project="https://github.com/dariusjecu/Picsome" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio5} title={"Picsome"} desc={"A dropshipping system using React, where the user can add the desired items to the shopping cart and create the checkout page where the user can see the final price, remove items that are no longer desired and complete the transaction."}/>
                <Project demo="https://dariusjecu.github.io/ToDoList/" project="https://github.com/dariusjecu/ToDoList" tech={[AiFillHtml5, DiCss3, SiJavascript, DiReact]} img={Portfolio6} title={"ToDoLIst"} desc={"A to do list that lets the user create a list in which he can add new items, delete old items that he no longer needs and cut items that he no longer needs at the moment, but that can be useful again in the future. I used localStorage in the creation of this application so that the user does not lose the list once created."}/>
            </div>
            <p className='space'></p>
            <a className='btn trans' href="https://github.com/dariusjecu/React-Projects" target="_blank">Check more projects on Github</a>
            <p className='space'></p>
        </section>
    )
}